#!/usr/bin/env php
<?php

require_once "vendor/autoload.php";

use Fulll\App\Fleet\Command\CreateFleetCommand;
use Fulll\App\Fleet\Command\LocalizeVehicleCommand;
use Fulll\App\Fleet\Command\RegisterVehicleCommand;
use Fulll\App\Fleet\Command\CreateUserCommand;
use Fulll\Infra\Database;
use Symfony\Component\Console\Application;

// In the context of this test, make sure all database config is set up.
(new Database())->initializeTables();

$commandName = $argv[1];
$params = array_splice($argv, 2);

$app = new Application();

switch ($commandName) {
    case 'create':
        $app->add(new CreateFleetCommand());
        break;

    case 'register-vehicle':
        $app->add(new RegisterVehicleCommand());
        break;

    case 'localize-vehicle':
        $app->add(new LocalizeVehicleCommand());
        break;

    case 'create-users':
        $app->add(new CreateUserCommand());
        break;
}

$app->run();
